---
title: "Conclusion"
output:
  bookdown::pdf_book:
    keep_tex: true
  pdf_document:
    toc: true
  bookdown::html_document2:
    toc: true
    toc_float: true
    highlight: tango
    code_folding: hide
    number_sections: true
    collapsed: true
header-includes: \usepackage{fvextra} \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
urlcolor: blue
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Conclusion

The aim of this group project was to have us work collaboratively on a chosen application domain. We used Github for file hosting and version control. We did research on the various types of datasets available and looked at the possible application domains we could look at. In this process, we found resources such as Kaggle, the UCI Machine Learning Repository and the Monash Time Series Repository. 

Through our research, we settled on financial data as our application domain due to its abundance and the rich opportunities it offers for applying techniques. Organising our team through WhatsApp, we split into teams to look at two different financial datasets: one on credit card fraud and one on Apple's stock data. This allowed us to gain an insight into the types of financial data that we could analyse for Project 1, and the challenges that may come with that. Analysis of the credit card fraud dataset allowed us to identify challenges with the data, and some ways to get around this. We saw that financial time series required too advanced techniques which require much background knowledge. We therefore settled on finding a dataset similar to the credit card fraud dataset, where we would demonstrate and build upon what we have learnt in this project.

# References

See the other files in this directory for references.
